### ISSUE TITLE
Umm. I need help.

### ISSUE THREAD

**Issue by Fnf4ever** [otomad/VegasScripts#80]
### Vegas Pro Version

Vegas Pro 21

### Otomad Helper Version

Latest

### Describe the bug

I'm currently trying to make a Sparta Remix with a Pitch Pattern I like to use and I'm getting this error whenever I try to run the Script into a Track.

### Logs

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at ScriptPortal.Vegas.Fade.set_Gain(Single value)
   at Otomad.VegasScript.OtomadHelper.V4.EntryPoint.GenerateOtomad() in c:\Users\vicki\AppData\Local\Temp\ipr0qnle.0.cs:line 1357
   at Otomad.VegasScript.OtomadHelper.V4.EntryPoint.Generate() in c:\Users\vicki\AppData\Local\Temp\ipr0qnle.0.cs:line 2614
   at Otomad.VegasScript.OtomadHelper.V4.EntryPoint.FromVegas(Vegas myVegas) in c:\Users\vicki\AppData\Local\Temp\ipr0qnle.0.cs:line 2784

**Comment by Evauation** [comment]
What does your settings for visual look like?

You probably have a setting related to the fade settings either in visual that's set incorrectly.

Shown from
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
at ScriptPortal.Vegas.Fade.set_Gain(Single value)

**Comment by Fnf4ever** [comment]
No Glow or Size Change. Stacatto. Velocity being mapped to 0-100. Audio tab didn't seem to work. Reset it and tried the Same CLip I used with audio attached to it and the error seemed to have went away. Thanks for the help, though ..
