### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Floppydisk123** [otomad/VegasScripts#9]
The error goes to something like this.

System.DivideByZeroException: Attempted to divide by zero.
   at System.Decimal.FCallDivide(Decimal& d1, Decimal& d2)
   at Otomad.VegasScript.OtomadHelper.V4.EntryPoint.MapVelocityToGain(Int32 velocity, MediaType media) in c:\Users\thepa\AppData\Local\Temp\3fktpn5n.0.cs:line 2339
   at Otomad.VegasScript.OtomadHelper.V4.EntryPoint.GenerateOtomad() in c:\Users\thepa\AppData\Local\Temp\3fktpn5n.0.cs:line 1372
   at Otomad.VegasScript.OtomadHelper.V4.EntryPoint.FromVegas(Vegas myVegas) in c:\Users\thepa\AppData\Local\Temp\3fktpn5n.0.cs:line 2659

**Comment by Floppydisk123** [comment]
Here's a pic version.

![Screenshot (36)](https://user-images.githubusercontent.com/111835326/186071368-fc037e7d-93a6-4db9-a159-20c071ad50c4.png)

**Comment by otomad** [comment]
It seems that you are using the mapping velocity feature and have entered the same value in both input boxes of velocity, such a value will not complete the mapping velocity operation.
